[package]
name = "bob"
edition = "2021"
version.workspace = true
authors.workspace = true
description.workspace = true

[dependencies]
clap = { version = "4.4.14", features = ["cargo"] }
uuid = { version = "1.7.0", features = ["v4"] }
