[workspace]
members = [ "bob","bootloader", "common", "kernel"]
resolver = "2"

[workspace.package]
version = "0.1.0"
authors = ["beersonthewall"]
description = "One day I'll be a real operating system :)."

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"

