cargo-features = ["per-package-target"]

[package]
name = "kernel"
edition = "2021"
version.workspace = true
authors.workspace = true
description.workspace = true
forced-target = "x86_64-unknown-none"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
