cargo-features = ["per-package-target"]

[package]
name = "bootloader"
edition = "2021"
version.workspace = true
authors.workspace = true
description.workspace = true
forced-target = "x86_64-unknown-uefi"

[dependencies]
log = "0.4.20"
uefi = "0.26.0"
uefi-services = "0.23.0"

